"""Prometheus metrics exporter for the trading engine."""

from prometheus_client import Counter, Gauge, Histogram, generate_latest, CONTENT_TYPE_LATEST

# ─── Gauges (current state) ───
balance_gauge = Gauge("trading_balance_usdt", "Current account balance in USDT")
drawdown_gauge = Gauge("trading_drawdown_pct", "Current drawdown percentage")
open_positions_gauge = Gauge("trading_open_positions", "Number of open positions")
regime_gauge = Gauge(
    "trading_regime",
    "Current market regime per symbol (1=TREND, 0.5=NEUTRAL, 0=RANGE)",
    ["symbol"],
)

# ─── Counters (cumulative) ───
signals_generated = Counter(
    "trading_signals_generated_total",
    "Total signals generated by strategies",
    ["strategy", "direction"],
)
signals_filtered = Counter(
    "trading_signals_filtered_total",
    "Total signals filtered out",
    ["filter_name"],
)
signals_accepted = Counter(
    "trading_signals_accepted_total",
    "Total signals that passed all filters",
    ["strategy"],
)
trades_opened = Counter(
    "trading_trades_opened_total",
    "Total trades opened",
    ["symbol", "direction"],
)
trades_closed = Counter(
    "trading_trades_closed_total",
    "Total trades closed",
    ["symbol", "reason"],
)
entry_failures = Counter(
    "trading_entry_failures_total",
    "Total trade entry failures by reason",
    ["reason"],
)
signal_stage_total = Counter(
    "trading_signal_stage_total",
    "Signals observed at each stage of the decision funnel",
    ["stage", "strategy", "timeframe"],
)
market_data_watchdog_events = Counter(
    "trading_market_data_watchdog_events_total",
    "Watchdog-triggered market data recovery events",
    ["event_type"],
)
market_data_stream_restarts = Counter(
    "trading_market_data_stream_restarts_total",
    "Market data restarts/fallbacks per stream",
    ["symbol", "timeframe", "reason"],
)

# ─── Histograms (distributions) ───
pnl_per_trade = Histogram(
    "trading_pnl_per_trade_usdt",
    "PnL per closed trade in USDT",
    buckets=[-50, -20, -10, -5, -2, -1, 0, 1, 2, 5, 10, 20, 50, 100],
)
signal_score_hist = Histogram(
    "trading_signal_score",
    "Distribution of signal scores",
    buckets=[0.3, 0.4, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0],
)
ai_latency_hist = Histogram(
    "trading_ai_latency_ms",
    "External AI call latency in milliseconds",
    buckets=[100, 250, 500, 1000, 2000, 5000, 10000],
)
market_data_stream_age_seconds = Gauge(
    "trading_market_data_stream_age_seconds",
    "Age of the latest update for a market-data stream in seconds",
    ["symbol", "timeframe"],
)
market_data_stream_recovering = Gauge(
    "trading_market_data_stream_recovering",
    "Whether a market-data stream is currently in recovery mode (1=yes, 0=no)",
    ["symbol", "timeframe"],
)

# ─── Trade Management metrics ───
trade_mgmt_events = Counter(
    "trading_trade_mgmt_events_total",
    "Trade management actions taken on open positions",
    ["action"],  # be_move, partial_reduce, time_stop, invalidation_exit, confirmed_trailing
)
trade_mgmt_r_at_exit = Histogram(
    "trading_trade_mgmt_r_at_exit",
    "R-multiple at the moment of management-triggered exit",
    buckets=[-3, -2, -1.5, -1, -0.5, 0, 0.25, 0.5, 1, 1.5, 2, 3, 5],
)
trade_mgmt_max_favorable_r = Histogram(
    "trading_trade_mgmt_max_favorable_r",
    "Maximum favorable R-multiple reached before exit",
    buckets=[0, 0.5, 1, 1.5, 2, 3, 5, 10],
)

ws_latency_ms = Histogram(
    "trading_ws_latency_ms",
    "Time from Binance candle generation to on_market_data processing in ms",
    buckets=[10, 50, 100, 250, 500, 1000, 5000, 10000],
)

order_execution_slippage = Histogram(
    "trading_order_execution_slippage_pct",
    "Difference between requested entry price and actual execution price in %",
    buckets=[-1.0, -0.5, -0.1, 0, 0.1, 0.5, 1.0, 5.0],
)

api_429_errors = Counter(
    "trading_api_429_errors_total",
    "Number of Binance API rate limit (429) errors",
)


def get_metrics_response():
    """Return raw Prometheus metrics bytes and content type."""
    return generate_latest(), CONTENT_TYPE_LATEST
